#!/bin/sh
# converting elf from gcc, to testbench img
# written by Hirofumi IWATO
# All Rights Reserved 2008. ASIP Solutions, Inc.

if [ $# -lt  1 ]; then
  echo "ERROR: Too few regular arguments."
  echo "       gccout2img [hoge.out]"
  exit
fi

export LANG=C
AWKSCRIPTDIR=$(dirname $(which gccout2img))

brownie32-elf-objdump -s $1  | gawk --posix 'BEGIN{shift=0;} /^ [[:digit:]]{4,}/{shift = length($1)-4;} {printf("%s\n", substr($0, 1, 41+shift));}' | gawk --posix -f ${AWKSCRIPTDIR}/gccout2im.awk > TestData.IM
brownie32-elf-objdump -s $1  | gawk --posix 'BEGIN{shift=0;} /^ [[:digit:]]{4,}/{shift = length($1)-4;} {printf("%s\n", substr($0, 1, 41+shift));}' | gawk --posix -f ${AWKSCRIPTDIR}/gccout2dm.awk > TestData.DM

